services:
  db:
    container_name: game_mysql
    image: mysql:9
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'card_game'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - ./mysql:data
