CREATE TABLE user (
    id SERIAL PRIMARY KEY,
    login VARCHAR(50) UNIQUE,
    email VARCHAR(255) UNIQUE, -- Nullable for OAuth users
    password VARCHAR(255), -- Can be NULL for users registered via OAuth
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE oauth_provider (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES user(id) ON DELETE CASCADE,
    provider VARCHAR(50) NOT NULL, -- union?
    provider_id VARCHAR(255) NOT NULL, -- ID provided by the OAuth provider
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (provider, provider_id)
);

CREATE TABLE session (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES user(id) ON DELETE CASCADE,
    session_token VARCHAR(255) UNIQUE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- A tie? nah! :D
CREATE TABLE game (
    id SERIAL PRIMARY KEY,
    winner_id INTEGER NOT NULL REFERENCES user(id) ON DELETE SET NULL,
    loser_id INTEGER NOT NULL REFERENCES user(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)